

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [ -f "/opt/homebrew/share/powerlevel10k" ]; then
  source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
  # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
fi

if [[ "$OSTYPE" =~ "darwin" ]] then
  
    # when put in zshenv it gets overwritten by tmux which calls /etc/profile again (login shell)
    # export PATH=$HOME/Library/Python/3.10/bin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/opt/homebrew/Cellar/coreutils/9.1/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/opt/mysql-client/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH

    eval "$(/opt/homebrew/bin/brew shellenv)"
    # brew автообновление конфигурация
    export HOMEBREW_NO_ENV_HINTS=1
    export HOMEBREW_AUTO_UPDATE_SECS=604800 

fi

if [[ "$OSTYPE" =~ "linux" ]] then

  if [ -f "$HOME/.linuxbrew/bin/brew" ]; then
    eval "$("$HOME/.linuxbrew/bin/brew" shellenv)"
  fi
  # brew автообновление конфигурация
  export HOMEBREW_NO_ENV_HINTS=1
  export HOMEBREW_AUTO_UPDATE_SECS=604800 
      
fi

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
# zstyle ':omz:update' frequency 13

# DISABLE_MAGIC_FUNCTIONS="true"
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
ZSH_CUSTOM=~/.config/zsh/custom/

# ПЛАГИНЫ	
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan,bold'
ZSH_AUTOCOMPLETE_HIGHLIGHT_STYLES=('fg=yellow' 'fg=cyan,bold') 
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(forward-char end-of-line)
	
plugins=(zsh-autosuggestions zsh-autocomplete zsh-syntax-highlighting chezmoi copybuffer sudo)

source $ZSH/oh-my-zsh.sh


# Askin configuration

#  History
# хранить историю в указанном файле
export HISTFILE=~/.zsh_history
# максимальное число команд, хранимых в сеансе
export HISTSIZE=1000
export SAVEHIST=$HISTSIZE
# включить историю команд
setopt APPEND_HISTORY
# убрать повторяющиеся команды, пустые строки и пр.
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

zstyle ':autocomplete:*' list-lines 5
zstyle ':autocomplete:*' widget-style menu-select

bindkey -M menuselect '\r' accept-line

bindkey '\e[A' history-beginning-search-backward
bindkey '\eOA' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward
bindkey '\eOB' history-beginning-search-forward
zle -A {.,}history-incremental-search-forward
zle -A {.,}history-incremental-search-backward

# export LANG=en_US.UTF-8

 if type brew &>/dev/null; then
   FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
   autoload -Uz compinit
   compinit
 fi

setopt correct
setopt autocd
setopt globdots

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
else
   export EDITOR='nvim'
fi
 



# source ~/.config/zsh/zshrc-nnn



