
# Default editor
export EDITOR='vim'
export VEDITOR='code'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
else
   export EDITOR='nvim'
fi

# PATH
typeset -U path
path=( "$HOME/.local/bin" "$HOME/bin" "$HOME/.cargo/bin" "/opt" $path )

if [[ "$OSTYPE" =~ "darwin" ]]; then
    # when put in zshenv it gets overwritten by tmux which calls /etc/profile again (login shell)
    export PATH=$HOME/Library/Python/3.10/bin:/opt/homebrew/opt/gnu-tar/libexec/gnubin:/opt/homebrew/Cellar/coreutils/9.1/libexec/gnubin:/opt/homebrew/bin:/opt/homebrew/opt/mysql-client/bin:/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH
    eval "$(/opt/homebrew/bin/brew shellenv)"
    # brew автообновление конфигурация
    export HOMEBREW_NO_ENV_HINTS=1
    export HOMEBREW_AUTO_UPDATE_SECS=604800 
fi

if [[ "$OSTYPE" == *"linux"* ]] && [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv zsh)"
  export HOMEBREW_NO_ENV_HINTS=1
  export HOMEBREW_AUTO_UPDATE_SECS=604800
fi




# OH-MY-ZSH

ZSH_CUSTOM=~/.config/zsh/custom/
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

ZSH_CUSTOM=~/.config/zsh/custom

if [[ -d "$ZSH_CUSTOM/themes/powerlevel10k/" && -f "$ZSH_CUSTOM/themes/powerlevel10k/powerlevel10k.zsh-theme" ]]; then
  ZSH_THEME="powerlevel10k/powerlevel10k"
  #echo "powerlevel10k"
else
  ZSH_THEME="robbyrussell"  # Fallback theme
  #echo "robbyrussell"
fi


# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
# zstyle ':omz:update' frequency 13

# DISABLE_MAGIC_FUNCTIONS="true"
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"


#  History
# хранить историю в указанном файле
export HISTFILE=~/.zsh_history
# максимальное число команд, хранимых в сеансе
export HISTSIZE=1000
export SAVEHIST=$HISTSIZE
# включить истоирю команд
setopt APPEND_HISTORY
# убрать повторяющиеся команды, пустые строки и пр.
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

# don't nice background tasks
setopt NO_BG_NICE
setopt NO_HUP
setopt NO_BEEP
# allow functions to have local options
setopt LOCAL_OPTIONS
# allow functions to have local traps
setopt LOCAL_TRAPS
# share history between sessions ???
setopt SHARE_HISTORY
# add timestamps to history
setopt EXTENDED_HISTORY
setopt PROMPT_SUBST
setopt CORRECT
setopt COMPLETE_IN_WORD
# adds history
setopt APPEND_HISTORY
# adds history incrementally and share it across sessions
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
# don't record dupes in history
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_VERIFY
setopt HIST_EXPIRE_DUPS_FIRST
# dont ask for confirmation in rm globs*
setopt RM_STAR_SILENT

setopt AUTOCD
setopt globdots


if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  autoload -Uz compinit
  compinit
fi



# PLUGINS

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root)
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=cyan,bold'
ZSH_AUTOCOMPLETE_HIGHLIGHT_STYLES=('fg=yellow' 'fg=cyan,bold') 
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(forward-char end-of-line)
	
plugins=(zsh-autosuggestions zsh-autocomplete zsh-syntax-highlighting chezmoi rbw copybuffer sudo)

zstyle ':autocomplete:*' list-lines 5
zstyle ':autocomplete:*' widget-style menu-select

source $ZSH/oh-my-zsh.sh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"

# export LANG=en_US.UTF-8
# source ~/.config/zsh/zshrc-nnn

zle -A {.,}history-incremental-search-forward
zle -A {.,}history-incremental-search-backward

bindkey -M menuselect '\r' accept-line
bindkey '\e[A' history-beginning-search-backward
bindkey '\eOA' history-beginning-search-backward
bindkey '\e[B' history-beginning-search-forward
bindkey '\eOB' history-beginning-search-forward

# edit command line in $EDITOR
bindkey '^e' edit-command-line

# delete word with ctrl+backspace
bindkey '^[[3;5~' backward-delete-word
# delete char with backspaces and delete
bindkey '^[[3~' delete-char
bindkey '^?' backward-delete-char




